import { z } from 'zod';

/** Risk level for a skill */
export type RiskLevel = 'read_only' | 'review_required' | 'destructive';

/** Execution mode */
export type ExecutionMode = 'dry_run' | 'confirmed';

/** Tool group identifier — matches WebflowAgentKit tool groups */
export type ToolGroup =
  | 'sites'
  | 'pages'
  | 'cms'
  | 'collections'
  | 'assets'
  | 'forms'
  | 'custom-code'
  | 'redirects'
  | 'seo'
  | 'webhooks'
  | 'products'
  | 'orders'
  | 'inventory'
  | 'audit-logs'
  | 'components';

/** Status of a skill execution step */
export type StepStatus = 'pending' | 'running' | 'completed' | 'failed' | 'skipped';

/** A recorded tool call within a skill execution */
export interface AuditRecord {
  /** Tool name called */
  toolName: string;
  /** Arguments passed to the tool */
  args: Record<string, unknown>;
  /** Result returned from the tool, or error message */
  result: unknown;
  /** Whether the call succeeded */
  success: boolean;
  /** Resource IDs that were created, updated, or deleted */
  changedResourceIds: string[];
  /** Timestamp of the call */
  timestamp: string;
}

/** A single step in a skill execution */
export interface StepResult {
  /** Step name */
  name: string;
  /** Step status */
  status: StepStatus;
  /** Audit records for tool calls made during this step */
  audit: AuditRecord[];
  /** Summary of what the step did */
  summary: string;
}

/** Execution plan generated by the skill */
export interface ExecutionPlan {
  /** Skill ID */
  skillId: string;
  /** Steps that will be executed */
  steps: Array<{ name: string; description: string; mutationCount: number }>;
  /** Total number of mutations (creates, updates, deletes) */
  totalMutations: number;
  /** Whether any steps write data */
  hasWrites: boolean;
  /** Execution mode (dry_run or confirmed) */
  mode: ExecutionMode;
}

/** Schema definition for a skill's input/output */
export interface SchemaRef {
  /** Zod schema for validation */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  schema: z.ZodType<any>;
  /** Human-readable description */
  description: string;
}

/** Canonical skill manifest */
export interface SkillManifest {
  /** Unique skill identifier (kebab-case) */
  id: string;
  /** Human-readable name */
  displayName: string;
  /** Semantic version */
  version: string;
  /** What the skill does */
  description: string;
  /** Tool groups this skill requires */
  requiredToolGroups: ToolGroup[];
  /** OAuth scopes required */
  requiredScopes: string[];
  /** Input schema */
  inputSchema: SchemaRef;
  /** Output schema */
  outputSchema: SchemaRef;
  /** Risk classification */
  riskLevel: RiskLevel;
  /** Default execution mode */
  defaultMode: ExecutionMode;
  /** Whether the skill supports rollback */
  supportsRollback: boolean;
}

/**
 * Skill interface — all skills must implement these methods.
 *
 * Skills orchestrate deterministic tool calls. AI reasoning may be
 * added by a caller separately; skills do not embed an LLM provider.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export interface Skill<TInput = Record<string, unknown>, TOutput = Record<string, unknown>> {
  /** The skill manifest */
  readonly manifest: SkillManifest; // eslint-disable-line @typescript-eslint/no-unused-vars

  /**
   * Validate input against the skill's schema.
   * @param input Raw input to validate
   * @returns Parsed and validated input
   * @throws ValidationError if input is invalid
   */
  validateInput(input: unknown): TInput;

  /**
   * Generate an execution plan without making any changes.
   * This is always safe — no API calls that write data.
   * @param input Validated input
   * @returns A deterministic execution plan
   */
  plan(input: TInput): Promise<ExecutionPlan>;

  /**
   * Execute the skill in dry-run mode.
   * May make read-only API calls to gather context, but must not
   * create, update, or delete any resources.
   *
   * @param input Validated input
   * @returns Step results with audit records
   */
  dryRun(input: TInput): Promise<StepResult[]>;

  /**
   * Execute the skill for real. Mutations are applied.
   * Only callable after plan() and explicit user confirmation.
   *
   * @param input Validated input
   * @param confirmationToken Token proving user confirmed the mutation plan
   * @returns Step results with audit records including changed resource IDs
   */
  execute(input: TInput, confirmationToken: string): Promise<StepResult[]>;

  /**
   * Roll back the skill execution if supported.
   * @param executionId The execution to roll back
   * @returns Step results for the rollback
   */
  rollback?(executionId: string): Promise<StepResult[]>;
}
